FROM python:3.11.8-slim-bookworm
RUN apt -y update && apt -y install gdal-bin libmagic1 && \
    rm -rf /var/lib/apt/lists/* && \
    apt clean

RUN python3 -m pip install --upgrade pip
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir
COPY docker/beat/start.sh ./start.sh
RUN chmod +x /app/start.sh
COPY . /app/
EXPOSE 8000
CMD ["/app/start.sh"]
