FROM python:3.11.8-slim-bookworm
RUN apt -y update && apt -y install gdal-bin libmagic1 && \
    rm -rf /var/lib/apt/lists/* && \
    apt clean
RUN python3 -m pip install --upgrade pip
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . /app/
RUN chmod +x /app/start.sh
CMD ["/app/start.sh"]
